# -*- coding: utf-8 -*-
"""Aula 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmjxYg9dH6oKowq7UQwbbsGXPnM2Z_A4

Diferença entre bit e byte
bit, é a menor unidade de formação, que o computador pode guardar, siginifica digito binário , pode ser composto por apenas 2 digitos 0 e 1 .
Byte , é uma unidade composta por 8 bit, há 256 combinações possiveis em uma sequencia de 0 e 1 .
```

5 Bytes possui 40 bits , pois é preciso multiplicar por 8 .
"""

2**0

print(2**1)
print(2**2)
print(2**3)
print(2**4)
print(2**5)
print(2**6)
print(2**7)

"""## Exercício 3: Binário para Decimal

Vamos converter os números binários para decimal usando a função `int(binary_string, 2)`.

### a) `00000001`
"""

# Convertendo '00000001' para decimal
binary_a = '00000001'
decimal_a = int(binary_a, 2)
print(f"O número binário {binary_a} em decimal é: {decimal_a}")

"""### b) `00001010`"""

# Convertendo '00001010' para decimal
binary_b = '00001010'
decimal_b = int(binary_b, 2)
print(f"O número binário {binary_b} em decimal é: {decimal_b}")

"""### c) `11111111`"""

# Convertendo '11111111' para decimal
binary_c = '11111111'
decimal_c = int(binary_c, 2)
print(f"O número binário {binary_c} em decimal é: {decimal_c}")