# -*- coding: utf-8 -*-
"""Aula 03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1DEL1r9l5x29is4nghciRaj3LOz20C3
"""

ord("z")

format(65, "08b")

print(format(ord("L"), "08b"))
print(format(ord("e"), "08b"))
print(format(ord("i"), "08b"))
print(format(ord("t"), "08b"))
print(format(ord("e"), "08b"))

for i in range(5):

chr(65)