# -*- coding: utf-8 -*-
"""exemplo 2 CDN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nYbnGIgFYK1PqCP55A9baYOo9hVPo7U

Lilian Sampaio
23/08/2026
Curso : Ciência de Dados para Negócio -Fatec
"""

print("Sou a Lilian , estudante de CDN -FATEC ")
print("Fiz markentig há 10 anos atrás e trabalho no setro comercial de uma empresa")
print("Minhas expectativas é mudar de emprego , ter um novo negócio e fucar ricaaaa ")
print("espero aprender de verdade e adquiri novos conceitos")
print (" Depois viajar o mundo todo , e dizer Olá Mundo")

"""O que é um Algoritimo ?

Um algoritimo é uma receita, que apresenta um passo a a passo de como relaizar uma determinada tarefa .

Para que serve o print?

Ele é um comando de execução, ele escreve ou apresenta um resultado .

Levantei da cama

Fiz minha oração

Tomei um banho

fui para a ginástica

tomei meu café

Coloquei meu uniforme

Fui trabalhar
"""



print("Nome:Lilian")
print("Curso:CDN -Fatec")
print("Matéria:Algoritimos")
print("Meta: Aprender")

"""Exercicio 7

 o erro está na falata\ das aspas

Cheguei no meu trabalho

liguei o computador

falei com os clientes

organizei a agenda

fiz o relatório

Comparei os exemplos dados pela IA e verifiquei a sequencia dos passos e observei que meus exemplos , também apresentam uma ordem lógica .
"""